exercism/abap

- abaplint_exercises.json
- abaplint_solutions.json
- config.json
- exercises/practice/two-fer/.docs/instructions.md
- exercises/practice/two-fer/.meta/config.json
- exercises/practice/two-fer/.meta/zcl_two_fer.clas.abap
- exercises/practice/two-fer/zcl_two_fer.clas.abap
- exercises/practice/two-fer/zcl_two_fer.clas.testclasses.abap
plus adjust some linting rules
> add two-fer exercise

- abaplint_solutions.json
- exercises/practice/hamming/.meta/zcl_hamming.clas.abap
- exercises/practice/hamming/zcl_hamming.clas.abap
- exercises/practice/hamming/zcl_hamming.clas.testclasses.abap
> hamming: use cx_parameter_invalid

- config.json
- exercises/practice/anagram/.docs/instructions.md
- exercises/practice/anagram/.meta/config.json
- exercises/practice/anagram/.meta/zcl_anagram.clas.abap
- exercises/practice/anagram/zcl_anagram.clas.abap
- exercises/practice/anagram/zcl_anagram.clas.testclasses.abap
used template exercise from 
https://github.com/exercism/problem-specifications/tree/main/exercises/anagram
> new exercise anagram

- config.json
- exercises/practice/darts/.docs/instructions.md
- exercises/practice/darts/.meta/config.json
- exercises/practice/darts/.meta/zcl_darts.clas.abap
- exercises/practice/darts/zcl_darts.clas.abap
- exercises/practice/darts/zcl_darts.clas.testclasses.abap
https://github.com/exercism/problem-specifications/tree/main/exercises/darts
> New Exercise: Darts

- config.json
- exercises/practice/prime-factors/.docs/instructions.md
- exercises/practice/prime-factors/.meta/config.json
- exercises/practice/prime-factors/.meta/zcl_prime_factors.clas.abap
- exercises/practice/prime-factors/zcl_prime_factors.clas.abap
- exercises/practice/prime-factors/zcl_prime_factors.clas.testclasses.abap
https://github.com/exercism/problem-specifications/tree/main/exercises/prime-factors
> New Exercise:  Prime Factors

- config.json
- exercises/practice/high-scores/.docs/instructions.md
- exercises/practice/high-scores/.meta/config.json
- exercises/practice/high-scores/.meta/zcl_high_scores.clas.abap
- exercises/practice/high-scores/zcl_high_scores.clas.abap
- exercises/practice/high-scores/zcl_high_scores.clas.testclasses.abap
https://github.com/exercism/problem-specifications/tree/main/exercises/high-scores
> New Exercise: High Scores

- .github/workflows/test.yml
- bin/test
extend original test script to test all exercises like in exercism production enviroment
Test Run https://github.com/marianfoo/abap/runs/4741973810?check_suite_focus=true
> Test Exercises with Docker Images in Github Action

- config.json
- exercises/practice/kindergarten-garden/.docs/instructions.md
- exercises/practice/kindergarten-garden/.meta/config.json
- exercises/practice/kindergarten-garden/.meta/tests.toml
- exercises/practice/kindergarten-garden/.meta/zcl_kindergarten_garden.clas.abap
- exercises/practice/kindergarten-garden/zcl_kindergarten_garden.clas.abap
- exercises/practice/kindergarten-garden/zcl_kindergarten_garden.clas.testclasses.abap
https://github.com/exercism/problem-specifications/tree/main/exercises/kindergarten-garden
> New Exercise: Kindergarten Garden

- config.json
- exercises/practice/scrabble-score/.docs/instructions.md
- exercises/practice/scrabble-score/.meta/config.json
- exercises/practice/scrabble-score/.meta/zcl_scrabble_score.clas.abap
- exercises/practice/scrabble-score/zcl_scrabble_score.clas.abap
- exercises/practice/scrabble-score/zcl_scrabble_score.clas.testclasses.abap
https://github.com/exercism/problem-specifications/tree/main/exercises/scrabble-score
How do i read this?
> New exercise: Scrabble score

- docs/ABOUT.md
- docs/INSTALLATION.md
- docs/LEARNING.md
- docs/RESOURCES.md
- docs/TESTS.md
- docs/config.json
Initial version of documentation
> Documentation

- config.json
- exercises/practice/nth-prime/.docs/instructions.md
- exercises/practice/nth-prime/.meta/config.json
- exercises/practice/nth-prime/.meta/zcl_nth_prime.clas.abap
- exercises/practice/nth-prime/zcl_nth_prime.clas.abap
- exercises/practice/nth-prime/zcl_nth_prime.clas.testclasses.abap
https://github.com/exercism/problem-specifications/tree/main/exercises/nth-prime
Errors because of preference of inline declaration, any options here?
`ltcl_nth_prime->test_first_prime` is failing
Test without Big Prime Number because of timeout, needs optimization
> New Exercise: Nth Prime

- exercises/shared/.docs/help.md
- exercises/shared/.docs/tests.md
This part of the documentation is used to generate files when using the Exercism CLI
- TEST.MD
- HELP.MD
> Update shared docs

- config.json
Align descriptions with standard
> Update exercise description

- config.json
closes #1 🎉 🥳 🎈 
@ErikSchierboom if all looks okay, we can merge?
We are planning an official launch stream on April 1st on YouTube, link will go up later today. When that is up, we can start buzzing and linking to that stream.
> Activate ABAP track!

- docs/TESTS.md
- Include instruction for using abapGit
- Add some details on testing
> Expand documentation for testing

- exercises/practice/hello-world/.meta/zcl_hello_world.clas.abap
- exercises/practice/hello-world/zcl_hello_world.clas.abap
- exercises/practice/hello-world/zcl_hello_world.clas.testclasses.abap
> Remove ADT output

- config.json
as @pokrakam mentioned in the stream, the difficulty is more "medium" than "easy"
> fix: change difficutly minesweeper to "medium"

- exercises/practice/minesweeper/zcl_minesweeper.clas.testclasses.abap
As I found out this morning that unit tests are quite prominent on the web (yay!), I'd like to replace them with my readability-oriented tests.
> More readable unit tests

- exercises/practice/custom-signs/.docs/hints.md
Third try, without subheadings
> Custom signs hints

- config.json
- exercises/practice/itab-basics/.docs/instructions.md
- exercises/practice/itab-basics/.meta/config.json
- exercises/practice/itab-basics/.meta/zcl_itab_basics.clas.abap
- exercises/practice/itab-basics/package.devc.xml
- exercises/practice/itab-basics/zcl_itab_basics.clas.abap
- exercises/practice/itab-basics/zcl_itab_basics.clas.testclasses.abap
- exercises/practice/itab-basics/zcl_itab_basics.clas.xml
Initial commit for itab-basics exercise
> Itab-basics commit

- CONTRIBUTING.md
> Fix link in Contribution Guidelines

- config.json
- exercises/practice/difference-of-squares/.docs/instructions.md
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/difference-of-squares/.meta/zcl_difference_of_squares.clas.abap
- exercises/practice/difference-of-squares/package.devc.xml
- exercises/practice/difference-of-squares/zcl_difference_of_squares.clas.abap
- exercises/practice/difference-of-squares/zcl_difference_of_squares.clas.testclasses.abap
- exercises/practice/difference-of-squares/zcl_difference_of_squares.clas.xml
> New Exercise: Difference of Squares

- docs/CLONE.md
Closes https://github.com/exercism/abap/issues/264
> Update package name and add troubleshooting

- docs/LEARNING.md
> Fix link to SAP Learning Journey

- abaplint.json
- exercises/practice/grains/zcl_grains.clas.testclasses.abap
yea, it will affect the students tests, but right now its not working
I dont really have time to fix packed numbers properly in the transpiler
> grains: workaround transpiler error

- concepts/basics/.meta/config.json
- concepts/basics/about.md
- concepts/basics/introduction.md
- exercises/concept/lasagna/.docs/hints.md
- exercises/concept/lasagna/.docs/instructions.md
- exercises/concept/lasagna/.docs/introduction.md
> Add docs for Lasagne exercise & Basics concept
